### ISSUE TITLE
Checklist before final release

### ISSUE THREAD

**Issue by manics** [IDR/k8s-analysis-deploy#1]
- [ ] GitLab Runner Helm chart https://gitlab.com/charts/charts.gitlab.io/merge_requests/120
- [ ] Helmfile hide secret logs https://github.com/roboll/helmfile/issues/79#issuecomment-378976978
- [ ] Gitlab Runner deployment image https://github.com/manics/kube-helm-docker/releases/tag/0.1.0
- [x] Restrict users who have access to GitLab CI/CD https://gitlab.com/openmicroscopy/incubator/k8s-analysis-deploy
- [x] Replace `SECRET_GITHUB_CLIENTID` `SECRET_GITHUB_CLIENTSECRET` with org OAuth app
- [x] Fix Elixir AAI callback URL
- [ ] Set default `Mirror user` in `Pull from a remote repository ` `Mirror repository` settings https://gitlab.com/openmicroscopy/incubator/k8s-analysis-deploy/settings/repository
- [x] Move https://github.com/manics/idr-analysis.openmicroscopy.org to IDR org if we're agreed on the setup
- [x] Use https://hub.docker.com/r/imagedata/idr-analysis.openmicroscopy.org/ Docker website image
- [x] Decide on size of shared read-write JupyterHub VAE scratch space (currently 1GB)
- [x] Consider setting resource limits on deployments

**Comment by joshmoore** [comment]
What's the proposed tag for the state of the checklist above?

**Comment by manics** [comment]
1.0.0 or 0.1.0 if we want to reserve 1.0.0 for the official release with IDR-0.5.0
